In [2]:
import os
import pandas as pd
import pickle

In [3]:
pkl_files=sorted([x for x in os.listdir('.') if 'SCNN_4_' in x and '200.pkl' in x])

In [4]:
tr_dict = dict()
te_dict = dict()

In [5]:
for curr in pkl_files:
    temp = pickle.load(open(curr,'r'))
    key = curr[7:-8]
    tr_dict[key] = [temp['train_conf_matrix'][x,x] for x in range(temp['train_conf_matrix'].shape[0])]
    te_dict[key] = [temp['test_conf_matrix'][x,x] for x in range(temp['test_conf_matrix'].shape[0])]

In [6]:
cat_list = ['airpl','autom','bird', 'cat','deer','dog','frog','horse', 'ship', 'truck']

In [7]:
train_df = pd.DataFrame.from_dict(tr_dict).T
train_df.columns = cat_list
train_df

,airpl,autom,bird,cat,deer,dog,frog,horse,ship,truck
bcdd_1,0.668414,0.898161,0.752910,0.724734,0.889963,0.807718,0.847348,0.625832,0.876000,0.953867
bcdd_1_200_bcdd_1_23,0.743284,0.867925,0.703691,0.675199,0.894632,0.809072,0.817529,0.757342,0.876259,0.953846
bcdd_1_200_birds_cats_deers_dogs_1_23,0.799476,0.864215,0.849019,0.679521,0.853284,0.817874,0.684347,0.804261,0.837333,0.949796
bcdd_1_200_data_batch_1,0.888557,0.952772,0.649225,0.729331,0.856857,0.837780,0.856311,0.900100,0.916098,0.958206
bcddh_1,0.595308,0.598529,0.294313,0.426529,0.504502,0.437712,0.045113,0.566732,0.255014,0.269525
bcddh_1_200_bcddh_1_23,0.629032,0.913235,0.798138,0.797540,0.821274,0.741706,0.769925,0.884287,0.836676,0.932619
birds_1,0.714710,0.933948,0.795200,0.407837,0.630277,0.764885,0.863955,0.849558,0.827881,0.906907
cats_1,0.833824,0.941358,0.506294,0.896400,0.709375,0.364929,0.776579,0.876692,0.735426,0.939759
data_batch_1,0.890547,0.950719,0.808140,0.594488,0.741742,0.601921,0.939806,0.849151,0.893659,0.943935
data_batch_2,0.837398,0.903674,0.699010,0.527638,0.757426,0.718623,0.978175,0.789474,0.939210,0.916751
data_batch_3,0.899396,0.956814,0.670466,0.564694,0.833333,0.736638,0.947853,0.926108,0.875130,0.944606
data_batch_4,0.831505,0.893043,0.520653,0.699795,0.805777,0.722821,0.940239,0.875637,0.935547,0.942014
data_batch_5,0.844181,0.895464,0.550420,0.561024,0.813440,0.685854,0.963265,0.880246,0.903290,0.958904
dogs_1,0.738532,0.913242,0.483728,0.418129,0.637879,0.885800,0.917910,0.818722,0.916540,0.928244
no_autos_1,0.875800,0.356601,0.326400,0.191800,0.454600,0.336800,0.989600,0.672000,0.657200,0.484848

In [8]:
test_df = pd.DataFrame.from_dict(te_dict).T
test_df.columns = cat_list
test_df

,airpl,autom,bird,cat,deer,dog,frog,horse,ship,truck
bcdd_1,0.599,0.844,0.679,0.651,0.837,0.769,0.791,0.555,0.801,0.900
bcdd_1_200_bcdd_1_23,0.690,0.800,0.633,0.608,0.843,0.795,0.769,0.653,0.821,0.920
bcdd_1_200_birds_cats_deers_dogs_1_23,0.724,0.780,0.767,0.622,0.780,0.773,0.620,0.710,0.741,0.889
bcdd_1_200_data_batch_1,0.793,0.905,0.502,0.563,0.723,0.706,0.785,0.810,0.824,0.887
bcddh_1,0.589,0.575,0.272,0.399,0.515,0.430,0.036,0.604,0.278,0.253
bcddh_1_200_bcddh_1_23,0.577,0.866,0.706,0.719,0.756,0.715,0.683,0.825,0.749,0.865
birds_1,0.612,0.898,0.728,0.310,0.503,0.656,0.826,0.753,0.743,0.818
cats_1,0.733,0.866,0.385,0.849,0.577,0.282,0.700,0.771,0.659,0.861
data_batch_1,0.820,0.873,0.693,0.462,0.609,0.495,0.907,0.757,0.814,0.881
data_batch_2,0.764,0.844,0.588,0.395,0.643,0.620,0.938,0.685,0.875,0.884
data_batch_3,0.836,0.876,0.517,0.451,0.704,0.630,0.883,0.827,0.790,0.900
data_batch_4,0.724,0.817,0.417,0.551,0.737,0.619,0.915,0.797,0.847,0.901
data_batch_5,0.760,0.829,0.439,0.436,0.691,0.588,0.930,0.794,0.801,0.912
dogs_1,0.626,0.827,0.355,0.298,0.482,0.873,0.883,0.707,0.830,0.860
no_autos_1,0.873,0.336,0.291,0.159,0.402,0.349,0.985,0.643,0.680,0.473

In [9]:
acc_dict = dict()
for curr in pkl_files:
    temp = pickle.load(open(curr,'r'))
    key = curr[7:-8]
    acc_dict[key] = [temp['train_acc'][1], temp['test_acc'][1]]

In [10]:
acc_df = pd.DataFrame.from_dict(acc_dict,).T
acc_df.columns=['Training', 'Testing']
acc_df

                                       Training  Testing
bcdd_1                                 0.798164   0.7426
bcdd_1_200_bcdd_1_23                   0.786744   0.7532
bcdd_1_200_birds_cats_deers_dogs_1_23  0.805763   0.7406
bcdd_1_200_data_batch_1                0.853500   0.7498
bcddh_1                                0.429356   0.3951
bcddh_1_200_bcddh_1_23                 0.810202   0.7461
birds_1                                0.778947   0.6847
cats_1                                 0.812643   0.6683
data_batch_1                           0.822400   0.7311
data_batch_2                           0.806600   0.7236
data_batch_3                           0.836400   0.7414
data_batch_4                           0.815300   0.7325
data_batch_5                           0.806200   0.7180
dogs_1                                 0.812159   0.6741
no_autos_1                             0.558484   0.5191

In [11]:
te_dict2 = {k:te_dict[k] for k in te_dict if 'data' in k}

In [12]:
test_df = pd.DataFrame.from_dict(te_dict2).T
test_df.columns = cat_list
test_df

,airpl,autom,bird,cat,deer,dog,frog,horse,ship,truck
bcdd_1_200_data_batch_1,0.793,0.905,0.502,0.563,0.723,0.706,0.785,0.810,0.824,0.887
data_batch_1,0.820,0.873,0.693,0.462,0.609,0.495,0.907,0.757,0.814,0.881
data_batch_2,0.764,0.844,0.588,0.395,0.643,0.620,0.938,0.685,0.875,0.884
data_batch_3,0.836,0.876,0.517,0.451,0.704,0.630,0.883,0.827,0.790,0.900
data_batch_4,0.724,0.817,0.417,0.551,0.737,0.619,0.915,0.797,0.847,0.901
data_batch_5,0.760,0.829,0.439,0.436,0.691,0.588,0.930,0.794,0.801,0.912