In [1]:
import os
import pandas as pd
import pickle

In [2]:
pkl_files=sorted([x for x in os.listdir('.') if 'SCNN_4_' in x and '200.pkl' in x])

In [3]:
tr_dict = dict()
te_dict = dict()

In [4]:
for curr in pkl_files:
    temp = pickle.load(open(curr,'r'))
    key = curr[7:-8]
    tr_dict[key] = [temp['train_conf_matrix'][x,x] for x in range(temp['train_conf_matrix'].shape[0])]
    te_dict[key] = [temp['test_conf_matrix'][x,x] for x in range(temp['test_conf_matrix'].shape[0])]

In [5]:
cat_list = ['airpl','autom','bird', 'cat','deer','dog','frog','horse', 'ship', 'truck']

In [6]:
train_df = pd.DataFrame.from_dict(tr_dict).T
train_df.columns = cat_list
train_df

,airpl,autom,bird,cat,deer,dog,frog,horse,ship,truck
bcdd_1,0.537271,0.763441,0.569200,0.745800,0.947400,0.712600,0.592366,0.470845,0.802941,0.828125
bcddh_1,0.502216,0.869832,0.597800,0.626000,0.906600,0.665000,0.758916,0.799800,0.733434,0.815789
birds_1,0.714710,0.933948,0.795200,0.407837,0.630277,0.764885,0.863955,0.849558,0.827881,0.906907
cats_1,0.833824,0.941358,0.506294,0.896400,0.709375,0.364929,0.776579,0.876692,0.735426,0.939759
data_batch_1,0.890547,0.950719,0.808140,0.594488,0.741742,0.601921,0.939806,0.849151,0.893659,0.943935
data_batch_2,0.837398,0.903674,0.699010,0.527638,0.757426,0.718623,0.978175,0.789474,0.939210,0.916751
data_batch_3,0.899396,0.956814,0.670466,0.564694,0.833333,0.736638,0.947853,0.926108,0.875130,0.944606
data_batch_4,0.831505,0.893043,0.520653,0.699795,0.805777,0.722821,0.940239,0.875637,0.935547,0.942014
data_batch_5,0.844181,0.895464,0.550420,0.561024,0.813440,0.685854,0.963265,0.880246,0.903290,0.958904
dogs_1,0.738532,0.913242,0.483728,0.418129,0.637879,0.885800,0.917910,0.818722,0.916540,0.928244
no_autos_1,0.875800,0.356601,0.326400,0.191800,0.454600,0.336800,0.989600,0.672000,0.657200,0.484848

In [7]:
test_df = pd.DataFrame.from_dict(te_dict).T
test_df.columns = cat_list
test_df

,airpl,autom,bird,cat,deer,dog,frog,horse,ship,truck
bcdd_1,0.478,0.718,0.531,0.689,0.943,0.709,0.589,0.397,0.741,0.792
bcddh_1,0.437,0.828,0.546,0.580,0.909,0.659,0.754,0.774,0.698,0.765
birds_1,0.612,0.898,0.728,0.310,0.503,0.656,0.826,0.753,0.743,0.818
cats_1,0.733,0.866,0.385,0.849,0.577,0.282,0.700,0.771,0.659,0.861
data_batch_1,0.820,0.873,0.693,0.462,0.609,0.495,0.907,0.757,0.814,0.881
data_batch_2,0.764,0.844,0.588,0.395,0.643,0.620,0.938,0.685,0.875,0.884
data_batch_3,0.836,0.876,0.517,0.451,0.704,0.630,0.883,0.827,0.790,0.900
data_batch_4,0.724,0.817,0.417,0.551,0.737,0.619,0.915,0.797,0.847,0.901
data_batch_5,0.760,0.829,0.439,0.436,0.691,0.588,0.930,0.794,0.801,0.912
dogs_1,0.626,0.827,0.355,0.298,0.482,0.873,0.883,0.707,0.830,0.860
no_autos_1,0.873,0.336,0.291,0.159,0.402,0.349,0.985,0.643,0.680,0.473

In [8]:
acc_dict = dict()
for curr in pkl_files:
    temp = pickle.load(open(curr,'r'))
    key = curr[7:-8]
    acc_dict[key] = [temp['train_acc'][1], temp['test_acc'][1]]

In [9]:
acc_df = pd.DataFrame.from_dict(acc_dict,).T
acc_df.columns=['Training', 'Testing']
acc_df

              Training  Testing
bcdd_1        0.730175   0.6587
bcddh_1       0.720864   0.6950
birds_1       0.778947   0.6847
cats_1        0.812643   0.6683
data_batch_1  0.822400   0.7311
data_batch_2  0.806600   0.7236
data_batch_3  0.836400   0.7414
data_batch_4  0.815300   0.7325
data_batch_5  0.806200   0.7180
dogs_1        0.812159   0.6741
no_autos_1    0.558484   0.5191